project:
  type: website

website:
  title: "Computing Using R & Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false